### ISSUE TITLE
NetworkDispatcher Exception

### ISSUE THREAD

**Issue by WenXin20** [Parallens/sword-stat#1]
Forge v14.23.4.2747-1.12.2
Sword Stat v0.5.2

I got the following error after swinging a plain Minecraft wooden sword. I do also have the mod [Quality Tools](https://minecraft.curseforge.com/projects/quality-tools) installed, and this only happened once I added Sword Stat. Can anything be done to fix this?

[Full Log](https://gist.github.com/WenXin20/55fb2b07af0104353588adab1d01131b)
`[21:44:54] [Netty Local Client IO #0/ERROR]: NetworkDispatcher exception java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?] at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final] at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?] at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.9.Final.jar:4.1.9.Final] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] [21:44:58] [main/INFO]: TAN configuration restored to local values [21:44:58] [main/INFO]: Client fetcher- all player data decached [21:45:10] [Server thread/INFO]: WenXin2 lost connection: Disconnected [21:45:10] [Server thread/INFO]: WenXin2 left the game`

**Comment by LaurenceWarne** [comment]
Apologies for the late reply, just looking at the error, I think this is probably due to too much information being stored (likely from lots of different mods) in the NBT of your sword such that its too big to be sent in packets from server/client. Sword Stat does store a lot of info in NBT, and this could conceivably be reduced so I'll put it onto my todo list.

I don't know how much information the Quality Tools mod stores in NBT but if you keep receiving this error it might be best to remove sword stat for now. Unfortunately, removing mods does not remove the NBT they store on items so will likely have to dispose of the sword(s) in question after removing the mods you choose to.

If you could link the modpack your using somewhere that would be helpful when I get to fixing this issue.

**Comment by WenXin20** [comment]
OK, thanks
